hostname: mothership
ssh_pwauth: true

users:
  - name: tbrereton
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIF/l5i336tQzxErNCrXSRaoyhcjthYOvvAfesHA/fHc noemail
    shell: /bin/bash

package_update: true
package_upgrade: true

packages:
  - git
  - curl
  - htop
  - cpu-checker

runcmd:
  - [ls, -l, /]
  - [sh, -xc, "echo $(date) ': hello world!'"]

# Reboot after all commands are executed
power_state:
  mode: reboot
